import { useEffect, useState } from "react";
import { ArrowRight, BookOpen, CalendarDays, Check, FlaskConical, HeartHandshake, Laptop, Lightbulb, MessageCircle, Trophy, Users } from "lucide-react";
import { fetchNoticias } from "../lib/contentApi";
import { SiteFooter, SiteHeader } from "../components/SiteChrome";

const principles = [[FlaskConical,"Pensamiento científico","Investigar, contrastar y convertir preguntas en aprendizajes."],[BookOpen,"Excelencia académica","Bases sólidas para aprender con autonomía durante toda la vida."],[HeartHandshake,"Formación humana","Ética, empatía y responsabilidad en cada decisión."]];
const levels = [
  {name:"Inicial",range:"3 a 5 años",title:"Explorar y descubrir",text:"El juego abre la puerta a la curiosidad, la autonomía y la convivencia.",image:"science-project.png",points:["Aprendizaje a través del juego","Desarrollo socioemocional","Exploración del entorno"]},
  {name:"Primaria",range:"1.° a 6.° grado",title:"Comprender y crear",text:"Las preguntas se transforman en conocimiento, criterio y nuevas maneras de expresarse.",image:"hero-classroom.png",points:["Lectura y razonamiento matemático","Ciencia basada en indagación","Arte, deporte y ciudadanía"]},
  {name:"Secundaria",range:"1.° a 5.° año",title:"Analizar y transformar",text:"Las ideas adquieren propósito mediante proyectos, investigación y liderazgo.",image:"science-project.png",points:["Profundización académica","Orientación vocacional","Proyectos de impacto social"]},
];
const modelTabs=[
  {name:"Aprendizaje activo",icon:Lightbulb,title:"El estudiante construye, no solo recibe.",text:"Clases basadas en preguntas, retos y experiencias que conectan el conocimiento con situaciones reales.",items:["Proyectos interdisciplinarios","Experimentación y resolución de problemas","Participación y reflexión constante"]},
  {name:"Acompañamiento",icon:Users,title:"Cada estudiante es conocido y acompañado.",text:"Tutoría cercana y comunicación continua con las familias para reconocer fortalezas y atender cada proceso.",items:["Seguimiento académico y emocional","Orientación personalizada","Alianza permanente con las familias"]},
  {name:"Innovación",icon:Laptop,title:"Tecnología con intención pedagógica.",text:"Recursos digitales, laboratorios y metodologías actuales al servicio de un aprendizaje más profundo.",items:["Ciudadanía digital responsable","Campus virtual integrado","Ciencia, creatividad y tecnología"]},
];
const newsIcons=[Trophy,CalendarDays,MessageCircle];

export default function Home(){const [activeModel,setActiveModel]=useState(0);const [activeLevel,setActiveLevel]=useState(0);const [noticias,setNoticias]=useState([]);const model=modelTabs[activeModel];const level=levels[activeLevel];
  useEffect(()=>{fetchNoticias().then(setNoticias)},[]);
  return <div className="bg-white"><SiteHeader active="Inicio"/><main>
  <section className="notebook-grid overflow-hidden"><div className="mx-auto grid min-h-[calc(100vh-80px)] max-w-[1380px] lg:grid-cols-[1.04fr_.96fr]">
    <div className="reveal-up flex flex-col justify-center px-6 py-20 sm:px-10 lg:px-20"><h1 className="font-display max-w-3xl text-5xl leading-[.97] text-emerald-950 sm:text-6xl xl:text-[5.5rem]">Educamos para comprender el mundo y mejorarlo<span className="text-amber-500">.</span></h1><p className="mt-8 max-w-xl text-lg leading-8 text-slate-600 sm:text-xl">Ciencia, pensamiento crítico y sensibilidad humana para que cada estudiante encuentre su voz y construya su futuro.</p><div className="mt-10 flex flex-wrap gap-4"><a href="#admision" className="action-primary">Conoce admisiones <ArrowRight size={18}/></a><a href="/nosotros" className="action-secondary">Nuestra propuesta <ArrowRight size={18}/></a></div></div>
    <div className="hero-photo group relative min-h-[480px] overflow-hidden lg:min-h-full"><img src="/images/hero-classroom.png" className="h-full w-full object-cover transition duration-1000 group-hover:scale-[1.03]" alt="Estudiantes del Colegio Max Planck en clase"/><div className="absolute bottom-6 left-6 right-6 border-l-4 border-amber-400 bg-emerald-950/90 p-5 text-white backdrop-blur sm:bottom-10 sm:left-10 sm:right-auto sm:max-w-sm"><strong className="font-display text-xl">Aprender deja huella</strong><p className="mt-1 text-sm leading-6 text-emerald-50/80">Una comunidad que acompaña cada descubrimiento.</p></div></div>
  </div></section>
  <section className="relative overflow-hidden bg-white py-20"><div className="absolute -left-24 top-0 size-72 rounded-full bg-amber-300/20 blur-3xl"/><div className="mx-auto max-w-7xl px-6 lg:px-8"><div className="mx-auto max-w-2xl text-center"><h2 className="font-display text-4xl text-emerald-950 sm:text-5xl">Principios que se viven todos los días.</h2><p className="mt-4 text-lg text-slate-600">Una formación que equilibra conocimiento, carácter y acción.</p></div><div className="mt-12 grid gap-5 md:grid-cols-3">{principles.map(([Icon,title,text],i)=><article key={title} className="group relative overflow-hidden border border-emerald-950/10 bg-white p-8 shadow-[0_18px_60px_rgba(3,64,48,.08)] transition duration-500 hover:-translate-y-2"><span className={`grid size-16 place-items-center rounded-full text-white shadow-lg ${i===0?"bg-emerald-600":i===1?"bg-amber-400 text-emerald-950":"bg-blue-800"}`}><Icon size={30}/></span><h3 className="font-display mt-7 text-2xl text-emerald-950">{title}</h3><p className="mt-3 leading-7 text-slate-600">{text}</p><span className={`absolute bottom-0 left-0 h-1 w-0 transition-all duration-500 group-hover:w-full ${i===0?"bg-emerald-500":i===1?"bg-amber-400":"bg-blue-700"}`}/></article>)}</div></div></section>
  <section className="relative overflow-hidden bg-emerald-950 py-20 text-white"><div className="absolute inset-0 notebook-grid-dark opacity-50"/><div className="relative mx-auto max-w-7xl px-6 lg:px-8"><div className="grid gap-10 lg:grid-cols-[.55fr_1.45fr]"><div><h2 className="font-display text-4xl sm:text-5xl">Aprender haciendo, pensar para la vida.</h2><p className="mt-5 text-lg leading-8 text-emerald-100/70">Elige un enfoque y descubre cómo convertimos curiosidad, colaboración y tecnología en aprendizaje profundo.</p></div><div><div className="grid gap-3 sm:grid-cols-3">{modelTabs.map((tab,i)=><button key={tab.name} onClick={()=>setActiveModel(i)} aria-pressed={activeModel===i} className={`group p-5 text-left transition duration-300 ${activeModel===i?"bg-amber-400 text-emerald-950 shadow-xl":"border border-white/15 bg-white/5 text-white hover:bg-white/10"}`}><tab.icon size={27}/><strong className="font-display mt-5 block text-lg">{tab.name}</strong></button>)}</div><div key={model.name} className="model-reveal mt-3 grid gap-8 border border-white/15 bg-white/5 p-7 backdrop-blur sm:p-9 lg:grid-cols-[1fr_1.2fr]"><div><h3 className="font-display text-3xl">{model.title}</h3><p className="mt-4 leading-7 text-emerald-100/75">{model.text}</p></div><div className="grid gap-3">{model.items.map((item,i)=><p key={item} className="flex items-center gap-4 border-b border-white/15 pb-3 font-semibold"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-emerald-500 text-xs">0{i+1}</span>{item}</p>)}</div></div></div></div></div></section>
  <section className="science-burst overflow-hidden py-24"><div className="mx-auto max-w-7xl px-6 lg:px-8"><div className="text-center"><h2 className="font-display text-4xl text-emerald-950 sm:text-5xl">Cada etapa, una nueva forma de descubrir.</h2><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-slate-600">Selecciona un nivel y conoce la experiencia que acompaña cada momento de su crecimiento.</p></div>
    <div className="mt-12 grid gap-3 sm:grid-cols-3">{levels.map((item,i)=>{const colors=["bg-emerald-600","bg-amber-400 text-emerald-950","bg-blue-800"];return <button key={item.name} onClick={()=>setActiveLevel(i)} aria-pressed={activeLevel===i} className={`level-tab group relative overflow-hidden px-6 py-6 text-left text-white transition duration-300 ${colors[i]} ${activeLevel===i?"-translate-y-2 shadow-2xl":"opacity-75 hover:-translate-y-1 hover:opacity-100"}`}><span className="relative z-10 flex items-center justify-between"><span><small className="block text-xs font-black tracking-widest">ETAPA 0{i+1}</small><strong className="font-display mt-1 block text-2xl">{item.name}</strong></span><ArrowRight className="transition group-hover:translate-x-1"/></span>{activeLevel===i?<span className="absolute bottom-0 left-1/2 h-3 w-6 -translate-x-1/2 rotate-45 translate-y-1/2 bg-inherit"/>:null}</button>})}</div>
    <article key={level.name} className="level-switch grid overflow-hidden bg-white shadow-[0_25px_80px_rgba(2,54,39,.16)] lg:grid-cols-[1.08fr_.92fr]"><div className="group relative min-h-[450px] overflow-hidden"><img src={`/images/${level.image}`} alt={`Estudiantes de nivel ${level.name}`} className="h-full w-full object-cover transition duration-700 group-hover:scale-[1.04]"/><div className="absolute bottom-6 left-6 rounded-full bg-white/95 px-5 py-3 font-bold text-emerald-950 shadow-lg">{level.range}</div></div><div className="flex flex-col justify-center p-8 sm:p-12 lg:p-14"><p className="text-sm font-black uppercase tracking-[.18em] text-amber-600">Nivel {level.name}</p><h3 className="font-display mt-3 text-4xl leading-tight text-emerald-950 sm:text-5xl">{level.title}</h3><p className="mt-5 text-lg leading-8 text-slate-600">{level.text}</p><div className="mt-8 grid gap-5">{level.points.map((point,i)=><div key={point}><div className="flex items-center justify-between gap-4"><p className="flex items-center gap-3 font-bold text-emerald-950"><span className={`grid size-9 place-items-center rounded-full text-white ${activeLevel===0?"bg-emerald-600":activeLevel===1?"bg-amber-400 text-emerald-950":"bg-blue-800"}`}><Check size={17}/></span>{point}</p><span className="text-xs font-bold text-slate-400">0{i+1}</span></div><div className="ml-12 mt-2 h-1 overflow-hidden bg-slate-100"><span className={`block h-full level-progress ${activeLevel===0?"bg-emerald-500":activeLevel===1?"bg-amber-400":"bg-blue-700"}`}/></div></div>)}</div><a href={`/niveles#${level.name.toLowerCase()}`} className="action-primary mt-9 self-start">Descubrir nivel {level.name} <ArrowRight size={18}/></a></div></article>
  </div></section>
  <section className="mx-auto grid max-w-[1380px] overflow-hidden bg-emerald-100 lg:grid-cols-2"><div className="group relative overflow-hidden"><img src="/images/campus.png" className="h-full min-h-[480px] w-full object-cover transition duration-1000 group-hover:scale-[1.04]" alt="Campus del Colegio Max Planck"/><div className="absolute right-0 top-0 h-28 w-28 rounded-bl-full bg-amber-400"/></div><div className="relative flex flex-col justify-center p-8 sm:p-14 lg:p-20"><span className="grid size-16 place-items-center rounded-full bg-emerald-700 text-white shadow-xl"><Users size={30}/></span><h2 className="font-display mt-7 text-4xl text-emerald-950 sm:text-5xl">El colegio también se vive fuera del aula.</h2><p className="mt-6 text-lg leading-8 text-slate-700">Proyectos, deporte, arte y encuentros familiares construyen una comunidad cercana, alegre y activa.</p><div className="mt-8 flex flex-wrap gap-3"><span className="rounded-full bg-white px-4 py-2 text-sm font-bold text-emerald-800">Arte y cultura</span><span className="rounded-full bg-white px-4 py-2 text-sm font-bold text-emerald-800">Deporte</span><span className="rounded-full bg-white px-4 py-2 text-sm font-bold text-emerald-800">Familias</span></div><a href="/nosotros" className="action-secondary mt-7 self-start">Conoce nuestra comunidad <ArrowRight size={18}/></a></div></section>
  <section id="campus-virtual" className="py-24"><div className="mx-auto grid max-w-7xl overflow-hidden bg-emerald-950 text-white lg:grid-cols-[1fr_1.1fr]"><div className="p-8 sm:p-14"><Laptop size={36} className="text-amber-400"/><h2 className="font-display mt-7 text-4xl sm:text-5xl">El aprendizaje continúa en línea.</h2><p className="mt-6 max-w-lg text-lg leading-8 text-emerald-100/70">Tareas, recursos, evaluaciones y comunicación escolar en un entorno digital seguro para estudiantes y familias.</p><a href="/campus" className="action-light mt-9">Conocer el campus virtual <ArrowRight size={18}/></a></div><div className="notebook-grid-dark flex min-h-[430px] items-center justify-center p-8"><div className="w-full max-w-lg border border-white/20 bg-white/10 p-5 transition duration-500 hover:-translate-y-2"><div className="bg-white p-7 text-emerald-950"><div className="flex items-center justify-between"><strong className="font-display text-xl">Hola, estudiante</strong><span className="size-3 rounded-full bg-emerald-500"/></div><p className="mt-2 text-sm text-slate-500">Tu aprendizaje de hoy</p><div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-3">{["Cursos","Tareas","Agenda","Notas","Recursos","Mensajes"].map(x=><span key={x} className="bg-emerald-50 p-4 text-center text-xs font-bold">{x}</span>)}</div></div></div></div></div></section>
  <section id="noticias" className="bg-slate-50 py-24"><div className="mx-auto max-w-7xl px-6 lg:px-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><h2 className="font-display text-4xl text-emerald-950 sm:text-5xl">Lo que está pasando en el colegio.</h2><p className="mt-4 text-lg text-slate-600">Logros, encuentros y experiencias de nuestra comunidad.</p></div><a href="#noticias" className="action-secondary">Ver todas las noticias <ArrowRight size={18}/></a></div><div className="mt-12 grid gap-6 md:grid-cols-12">{noticias.map((n,i)=>{const Icon=newsIcons[i%newsIcons.length];const fecha=n.fecha?new Date(n.fecha).toLocaleDateString("es-PE",{day:"numeric",month:"long",year:"numeric"}):"";return <article key={n.id} className={`group overflow-hidden bg-white shadow-[0_15px_50px_rgba(3,54,42,.08)] transition duration-500 hover:-translate-y-2 ${i===0?"md:col-span-6":"md:col-span-3"}`}><div className="overflow-hidden"><img src={`/images/${n.imagen}`} alt="" className={`w-full object-cover transition duration-700 group-hover:scale-105 ${i===0?"h-80":"h-56"}`}/></div><div className="p-6"><div className="flex items-center gap-2 text-sm font-bold text-amber-600"><Icon size={17}/> {fecha}</div><h3 className="font-display mt-4 text-2xl text-emerald-950">{n.titulo}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{n.resumen}</p><ArrowRight className="mt-5 text-emerald-700 transition group-hover:translate-x-2"/></div></article>})}</div></div></section>
  <section className="relative overflow-hidden bg-emerald-950 py-20 text-white"><div className="absolute -right-20 -top-24 size-80 rounded-full border-[55px] border-emerald-700/30"/><div className="relative mx-auto grid max-w-7xl items-center gap-10 px-6 lg:grid-cols-[.6fr_1.4fr] lg:px-8"><div><p className="font-display text-8xl leading-none text-amber-400">“</p><h2 className="font-display -mt-6 text-3xl">Una comunidad que se escucha.</h2></div><blockquote className="m-0 border-l border-amber-400 pl-8"><p className="font-display text-2xl leading-10 sm:text-3xl">Aquí cada estudiante puede preguntar, equivocarse y volver a intentarlo sabiendo que alguien lo acompaña.</p><footer className="mt-6 text-sm font-bold text-amber-300">Familia de Primaria · Comunidad Max Planck</footer></blockquote></div></section>
  <section id="admision" className="bg-amber-400 px-6 py-16"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 md:flex-row md:items-center"><div><h2 className="font-display text-4xl text-emerald-950 sm:text-5xl">Admisiones 2027 abiertas.</h2><p className="mt-3 text-lg font-medium text-emerald-950/75">Te acompañamos a iniciar una nueva etapa para tu hijo.</p></div><a href="/admision" className="action-primary shrink-0">Ver proceso de admisión <ArrowRight size={18}/></a></div></section>
</main><SiteFooter/></div>}
